#General
work dir: sample_size_10
slimfile: example_model.slim

sample sizes: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
ploidy: 2

#Simulation
reps: 2500
slim path: slim