#General
work dir: example_run
slimfile: example_model.slim 

scenarios: ["neutral", "hard", "soft"]
mut types: [2]
sample sizes: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
ploidy: 2
win_size: 51

#Simulation
reps: 1000
slim path: slim